---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/6022c03a5996b80015933b17/webhook/forestry'
sections:
- type: document
  path: site-metadata.json
  label: Site Configuration
  templates:
  - config
- type: directory
  path: src/data/team
  label: Person
  create: all
  match: '**/*'
  new_doc_ext: yaml
  templates:
  - person
- type: directory
  path: src/data/categories
  label: Category
  create: all
  match: '**/*'
  new_doc_ext: yaml
  templates:
  - category
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: '**/*'
  new_doc_ext: md
  templates:
  - page
  - post
  - advanced
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
